name: Create deployment

on: pull_request

jobs:
  asd:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: octokit/request-action@v2.1.7
        id: create-deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments
          owner: ${{ github.event.repository.owner }}
          repo: ${{ github.event.repository.name }}
          ref: asd
          environment: dev
      - uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses
          owner: joonashak
          repo: workflow-testing
          deployment_id: ${{ fromJson(steps.create-deployment.outputs.data).id }}
          ref: asd
          environment: dev
          state: success
          environment_url: https://github.com/joonashak/workflow-testing/pulls
      - run: echo ${{ GITHUB_REPOSITORY }}
