name: Create deployment

on: pull_request

jobs:
  asd:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments
          owner: joonashak
          repo: workflow-testing
          ref: ${{ github.ref }}
          environment: asd
      - uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments
          owner: joonashak
          repo: workflow-testing
          ref: ${{ github.ref }}
          environment: asd
          status: success
          environment_url: https://github.com/joonashak/workflow-testing/pulls
