name: Create deployment

on: push

jobs:
  asd:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: octokit/request-action@v2.1.7
        id: create-deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/deployments
          ref: asd
          environment: dev
          auto_merge: false
      - run: echo ${{ steps.create-deployment.outputs.data }}
      - uses: octokit/request-action@v2.1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses
          owner: joonashak
          repo: workflow-testing
          deployment_id: ${{ fromJson(steps.create-deployment.outputs.data).id }}
          ref: asd
          environment: dev
          state: success
          environment_url: https://github.com/joonashak/workflow-testing/pulls
      - run: echo ${GITHUB_REPOSITORY}
