name: Release

on:
  push:

jobs:
  asd:
    name: Triggering another workflow
    uses: ./.github/workflows/trigger_by_workflow.yaml
    with:
      fun: "a lot, please"
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create GitHub release
        if: ${{ steps.npm-publish.outputs.type != 'none' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ format('v{0}', '0.1.0') }}
